version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      PGDATA: /var/lib/postgresql/data/db-files/
  web:
   #build: . - для тестов =)
    build:
      context: .
      dockerfile: Dockerfile_web
    restart: always
    depends_on:
      - db
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000  
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
